In [23]:
# Question 0: Make a function that prints out "I Love IS 115/505!" and then call it
def lovePhrase():
  print("I Love IS 115/505!")

lovePhrase()

I Love IS 115/505!

In [3]:
#Background: You are currently staying at Camp Green Lake where every "Camper" is required to dig a 5 foot deep hole daily. Fortunately for you
# the warden, Louise Walker, heard you know some programming and has a slightly less labor intensive job for you. Camp Green Lake knows the depths
# of all their holes but the radius varies, and they need to report exactly how many cubic feet have been moved in the month of may. This
# would take weeks to do by hand but using your coding skills you can do it in a few minutes.


# Question 1: Create a function that will recieve a hole/cylinder's radius as an input and then returns the volume of that cylinder.
# Use this function to show the volume of a cylinder with a radius of 5 ft and then print out the result as a f string that says
# "Area: {area_variable} cubed feet." where the area variable is the value your function returns. Round your answer to the two decimal places.
# For the purpose of this question you can use the value of 3.1415 as a constant for pi and 5 is a constant for height.
# Formula for the volume of a cylinder: pi*r^2*H  r = radius H = height
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/aylinggq/BCIS-321/refs/heads/main/Holes-Aylin_Gomez_Quezada.csv')
df

rows = []
dirt =0
total_dirt = 0
depth =5
pi = 3.14

def volume (radius, depth):
  vol=((radius**2)*pi)*depth
  return vol

df

    Unnamed: 0     Name  Radius        Date
0            0  CaveMan     4.2  05-07-2020
1            1    X Ray     5.1  05-07-2020
2            2     Zero     8.4  05-07-2020
3            3   Armpit     8.0  05-07-2020
4            4  CaveMan     3.8  05-08-2020
5            5    X Ray     6.5  05-08-2020
6            6     Zero     9.2  05-08-2020
7            7   Armpit     7.7  05-08-2020
8            8  CaveMan     3.2  05-09-2020
9            9    X Ray     4.7  05-09-2020
10          10     Zero     7.1  05-09-2020
11          11   Armpit     6.6  05-09-2020
12          12  CaveMan     5.3  05-10-2020
13          13    X Ray     5.3  05-10-2020
14          14     Zero     9.9  05-10-2020
15          15   Armpit     7.9  05-10-2020
16          16  CaveMan     4.9  05-11-2020
17          17    X Ray     4.5  05-11-2020
18          18     Zero     3.2  05-11-2020
19          19   Armpit     9.9  05-11-2020

In [4]:
# Question 2: Here we have a list of the holes dug in the month of May.
# Create a loop that will use your volume generating function  and then find the total abount of cubic feet of dirt moved in May. Save that
# value rounded to the second decimal place in a value called total_dirt and then output it.


for row in range (0,20):
  depth = float (df.iloc[row,2])
  dirt = volume(5, depth)
  total_dirt = total_dirt + dirt
  print (f'The amount of dirt is {dirt:.2f} cubic feet')

print(f'The total amount of dirt is {total_dirt:.2f} cubic feet')

The amount of dirt is 329.70 cubic feet
The amount of dirt is 400.35 cubic feet
The amount of dirt is 659.40 cubic feet
The amount of dirt is 628.00 cubic feet
The amount of dirt is 298.30 cubic feet
The amount of dirt is 510.25 cubic feet
The amount of dirt is 722.20 cubic feet
The amount of dirt is 604.45 cubic feet
The amount of dirt is 251.20 cubic feet
The amount of dirt is 368.95 cubic feet
The amount of dirt is 557.35 cubic feet
The amount of dirt is 518.10 cubic feet
The amount of dirt is 416.05 cubic feet
The amount of dirt is 416.05 cubic feet
The amount of dirt is 777.15 cubic feet
The amount of dirt is 620.15 cubic feet
The amount of dirt is 384.65 cubic feet
The amount of dirt is 353.25 cubic feet
The amount of dirt is 251.20 cubic feet
The amount of dirt is 777.15 cubic feet
The total amount of dirt is 9843.90 cubic feet

In [8]:
# Question 3: The warden also wants to be able to pull out the info about holes dug based on specific criteria.
# Using the Pandas library read the Holes.csv into this cell

def filtered_list(df, column_name, filter_value):
  return df[df[column_name] == filter_value]

filtered_list(df, 'Name', 'Zero')



# Create a function that will recieve 3 parameters: a dataframe & a string representing the column name & a string representing the filter value
# then output a filtered dataframe that only displays info for the name matching the string that was passed in.
# Call this function with the correct parameters to return all holes dug by "Zero" (output the resulting dataframe)

    Unnamed: 0  Name  Radius        Date
2            2  Zero     8.4  05-07-2020
6            6  Zero     9.2  05-08-2020
10          10  Zero     7.1  05-09-2020
14          14  Zero     9.9  05-10-2020
18          18  Zero     3.2  05-11-2020

In [16]:
#Question 4: Finally we want to know the details about all the holes that were dug on May 7 2020. Use the fuction you made in the last
# problem to find only the records where date = "05-07-2020"

filtered_list(df, 'Date', '05-07-2020')

   Unnamed: 0     Name  Radius        Date
0           0  CaveMan     4.2  05-07-2020
1           1    X Ray     5.1  05-07-2020
2           2     Zero     8.4  05-07-2020
3           3   Armpit     8.0  05-07-2020